version: '3.8'

services:
  frontend:
    image: semi22/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: backend:latest
    ports:
      - "4000:4000"
