# Use an official Node.js image as the base image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json (if available) to the working directory
COPY package*.json ./

# Install project dependencies
RUN npm install

# Expose port 3000 for the React app
EXPOSE 3000

# Define the command to run when the container starts
CMD ["npm", "start"]
