name: deploy-recette

on:
  push:
    branches: [ "recette" ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_push_to_registry:
    name: Push to Azure Registry
    runs-on: [ ubuntu-latest ]
    steps:
      - name: check out the repo
        uses: actions/checkout@v2

      - name: set up Docker builder
        uses: docker/setup-buildx-action@v1

      - name: log into Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: pomelo.azurecr.io
          username: ${{ secrets.AZURE_CR_USERNAME }}
          password: ${{ secrets.AZURE_CR_PASSWORD }}

      - name: push to Azure Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.envs
          build-args: |
            ENVIRONMENT=recette
            BK_URL=https://recette.backend.dollycar.hello-pomelo.ovh
          push: true
          tags: |
            pomelo.azurecr.io/dollycar-backoffice-recette:${{ github.sha }}
            pomelo.azurecr.io/dollycar-backoffice-recette:latest
  deploy:
    name: Deploy to VPS
    runs-on: [ ubuntu-latest ]
    needs: build_push_to_registry
    steps:
    - name:  Connecting via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.RECETTE_HOST }}
        username: ${{ secrets.RECETTE_USER }}
        key: ${{ secrets.RECETTE_KEY }}
        port: 22
        script: |
          docker login -u ${{ secrets.AZURE_CR_USERNAME }} -p ${{ secrets.AZURE_CR_PASSWORD }} pomelo.azurecr.io
          docker pull pomelo.azurecr.io/dollycar-backoffice-recette:latest
          docker logout pomelo.azurecr.io
          cd dollycar-backoffice-recette
          git pull -q
          docker compose -f docker-compose.envs.yml up -d